### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by Kabenla** [thehyve/transmart-core#39]
OS: Ubuntu 16.04
Gradle: version 4.0
Groovy: 2.4.11
Java: java version "1.8.0_131" (Oracle)

Following the instructions, the build fails after running gradle :transmartApp:bootRepackage with the following message 

![1 transmart transmart-171-8103 transmart-core ssh 2017-06-15 12-56-19](https://user-images.githubusercontent.com/5950671/27194798-9fb4c168-51c9-11e7-8325-60bca11c4052.png)

**Comment by gijskant** [comment]
Dear @Kabenla, it seems that your gradle version is too new. Transmart should build fine with gradle 2.13. I recommend either to use `sdk use gradle 2.13` before building Transmart (see http://sdkman.io/install.html for instructions on how to install `sdk`) or to use the gradle wrapper:
```bash
gradle wrapper
./gradlew :transmartApp:bootRepackage
```
Hopefully that will make it work for you.

**Comment by Kabenla** [comment]
Thanks for the information.  I am was able to build with an earlier version of gradle.
