### ISSUE TITLE
Installation instructions seem to be outdated

### ISSUE THREAD

**Issue by lukaszimmermann** [thehyve/transmart-core#400]
When I call the following snippet:
```
# Fetch artefacts from Maven
TRANSMART_VERSION=17.1-HYVE-5.2
curl -f -L https://repo.thehyve.nl/service/local/repositories/releases/content/org/transmartproject/transmart-api-server/${TRANSMART_VERSION}/transmart-server-${TRANSMART_VERSION}.war -o transmart-server-${TRANSMART_VERSION}.war && \
# Run it with:
java -jar transmart-server-${TRANSMART_VERSION}.war
```
I am returned a 404 HTTP code. I suspect that the artifact with the version
`17.1-HYVE-5.2` is not in the Nexus repository? 

I took the snippet from the `dev` branch from the file `docs/README.md`
for installing the tranSMART server.

**Comment by gijskant** [comment]
Thanks for reporting. Could you check if the updated instructions in #407 work for you?

**Comment by lukaszimmermann** [comment]
The URL to tranSMART API Server should be:
```
https://repo.thehyve.nl/service/local/repositories/releases/content/org/transmartproject/transmart-api-server/17.1-HYVE-5.9-RC1/transmart-api-server-17.1-HYVE-5.9-RC1.war
```
in the documentation. Currently, it is:
```
https://repo.thehyve.nl/service/local/repositories/releases/content/org/transmartproject/transmart-api-server/17.1-HYVE-5.9-RC1/transmart-server-17.1-HYVE-5.9-RC1.war
```

**Comment by gijskant** [comment]
I updated the URL for `transmart-server` now. Both URLs should work now: one for `transmart-server` and one for `transmart-api-server`.

**Comment by lukaszimmermann** [comment]
Ok, thanks. Guess this can be closed then.
