### ISSUE TITLE
Not all nodes represented in tree when using trial visits

### ISSUE THREAD

**Issue by jochemb** [thehyve/transmart-core#48]
This is and issue for transmart-batch.

When loading data with trial visits to a subfolder that has no "normal" concepts, the data is not shown in the tree. The concept dimension is missing the subfolder that should contain the concepts with trial visits.

To reproduce:
* download the Training study for the python client: https://github.com/thehyve/transmart-tutorials/tree/master/resources/python_client/Training 
* and in the column map file remove the row with the data label "Method"  (or set to OMIT).

**Comment by ewelinagr** [comment]
@jochemb There was a fix for similar issue: https://github.com/thehyve/transmart-core/pull/55, it is now merged into master
