### ISSUE TITLE
Move the Constraint class to transmart-core-api

### ISSUE THREAD

**Issue by gijskant** [thehyve/transmart-core#75]
Currently, the class that defines the public API for queries, is part of transmart-core-db:
`org.transmartproject.db.multidimquery.query.Constraint`.
There is an empty interface `org.transmartproject.core.multidimquery.MultiDimConstraint`.
Ideally, the former should replace the latter, allowing for reuse, and reducing the dependency of transmart-rest-api on transmart-core-db.
The main bottleneck for this transition is the dependency on domain class knowledge for binding fields.
The proper approach would be to move lookup of fields to the code that uses/applies the constraint, instead of the binding code. Consequently, the `Field` class should have a `String` field `dimension` instead of one typed `Dimension`.
The function `static Field bindField(Object object, String name, Map values)` can be moved to the query builder implementation. That means that when specifying an invalid field, an exception will not be thrown at binding time, but during query building.

**Comment by gijskant** [comment]
Work in this direction has started in the `luke-dev` branch here: 027502a8256cdcedf440cb474d57143130a2030e.

**Comment by forus** [comment]
@gijskant should we close this one?

**Comment by gijskant** [comment]
Fixed by #173.
